security:
    encoders:
        Zubi\UserBundle\Entity\User: plaintext


    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: {class: Zubi\UserBundle\Entity\User, property: email}

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login_firewall:
            pattern:  ^/login$
            anonymous: ~

        register_firewall:
            pattern: ^/profile/register
            anonymous: ~

        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                check_path: /login_check
                login_path: /login
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/profile/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/profile/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/device/collect, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile/device, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/device, roles: ROLE_USER }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
