Zubi\DeviceBundle\Entity\Station:
  type: entity
  table: Stacje_pogodowe
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    hash:
      type: string
      length: 255
      column: Hash
    version:
      type: string
      length: 255
      column: Wersja
    country:
      type: string
      length: '4'
      column: Kraj
    city:
      type: string
      length: 255
      column: Miasto
    street:
      type: string
      length: 255
      column: Ulica
    longitude:
      type: float
      column: Dlugosc
    latitude:
      type: float
      column: Szerokosc
  lifecycleCallbacks: {  }
  oneToMany:
    measurements:
      targetEntity: Measurement
      mappedBy: station
  manyToOne:
    user:
      targetEntity: \Zubi\UserBundle\Entity\User
      inversedBy: stations
      joinColumn:
        name: Id_Uzytkownika
        referencedColumnName: id
